version: 3

tasks:
  better-commits:install:
    desc: Install better commits
    cmds:
      - npm install -g better-commits
    status:
      - command -v better-commits

  branch:new: better-branch
  commit: better-commits
  pr:create: gh pr create --assignee "@me" --base "main" -w

  pre-commit:install: pre-commit install
  pre-commit:run: pre-commit run --all-files --color always --show-diff-on-failure

  tflint: tflint --recursive

  ci:clean-workflow-runs:
    desc: Clean up workflow runs
    vars:
      WORKFLOW_RUNS: 
        sh: gh run list --limit 1000 --status="completed" --json "databaseId" --jq ".[] | select(.databaseId != null) | .databaseId"
    cmds:
      - echo "$WORKFLOW_RUNS" # | xargs -r gh run delete 
      - for:
          var: WORKFLOW_RUNS
        cmd: |
          gh run delete {{ .ITEM }}